import { boolean, integer, jsonb, pgTable, text, timestamp } from "drizzle-orm/pg-core"

export const user = pgTable("user", {
  id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("emailVerified").notNull().default(false), image: text("image"), whatsapp: text("whatsapp"), jobTitle: text("jobTitle"), lastAccessAt: timestamp("lastAccessAt", { withTimezone: true }), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull().defaultNow(),
})
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expiresAt", { withTimezone: true }).notNull(), token: text("token").notNull().unique(), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull().defaultNow(), ipAddress: text("ipAddress"), userAgent: text("userAgent"), userId: text("userId").notNull() })
export const account = pgTable("account", { id: text("id").primaryKey(), accountId: text("accountId").notNull(), providerId: text("providerId").notNull(), userId: text("userId").notNull(), accessToken: text("accessToken"), refreshToken: text("refreshToken"), idToken: text("idToken"), accessTokenExpiresAt: timestamp("accessTokenExpiresAt", { withTimezone: true }), refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt", { withTimezone: true }), scope: text("scope"), password: text("password"), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull().defaultNow() })
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expiresAt", { withTimezone: true }).notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull().defaultNow() })
export const organizations = pgTable("organization", { id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull().unique(), logo: text("logo"), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(), metadata: text("metadata") })
export const members = pgTable("member", { id: text("id").primaryKey(), organizationId: text("organizationId").notNull(), userId: text("userId").notNull(), role: text("role").notNull().default("member"), status: text("status").notNull().default("active"), lastAccessAt: timestamp("lastAccessAt", { withTimezone: true }), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow() })
export const developments = pgTable("development", { id: text("id").primaryKey(), userId: text("userId").notNull(), organizationId: text("organizationId"), name: text("name").notNull(), client: text("client").notNull(), status: text("status").notNull().default("em_andamento"), deliveryDate: text("deliveryDate").notNull(), masterProgress: integer("masterProgress").notNull().default(0), data: jsonb("data").notNull().default({}), workflowStatus: text("workflowStatus").notNull().default("rascunho"), lastEditorId: text("lastEditorId"), approvedVersion: integer("approvedVersion"), approvedBy: text("approvedBy"), approvedAt: timestamp("approvedAt", { withTimezone: true }), version: integer("version").notNull().default(1), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull().defaultNow() })
export const databookFiles = pgTable("databook_file", { id: text("id").primaryKey(), userId: text("userId").notNull(), developmentId: text("developmentId").notNull(), folder: text("folder").notNull(), name: text("name").notNull(), pathname: text("pathname").notNull().unique(), contentType: text("contentType"), sizeBytes: integer("sizeBytes").notNull().default(0), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow() })
export const organizationInvitations = pgTable("organization_invitation", { id: text("id").primaryKey(), organizationId: text("organizationId").notNull(), email: text("email").notNull(), name: text("name").notNull(), role: text("role").notNull(), tokenHash: text("tokenHash").notNull().unique(), status: text("status").notNull().default("pending"), expiresAt: timestamp("expiresAt", { withTimezone: true }).notNull(), invitedBy: text("invitedBy").notNull(), acceptedBy: text("acceptedBy"), acceptedAt: timestamp("acceptedAt", { withTimezone: true }), canceledAt: timestamp("canceledAt", { withTimezone: true }), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow() })
export const developmentReviews = pgTable("development_review", { id: text("id").primaryKey(), developmentId: text("developmentId").notNull(), organizationId: text("organizationId").notNull(), version: integer("version").notNull(), status: text("status").notNull(), editorId: text("editorId").notNull(), validatorId: text("validatorId"), comment: text("comment"), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow() })
export const auditLogs = pgTable("audit_log", { id: text("id").primaryKey(), organizationId: text("organizationId").notNull(), actorId: text("actorId").notNull(), action: text("action").notNull(), entityType: text("entityType").notNull(), entityId: text("entityId").notNull(), metadata: jsonb("metadata").notNull().default({}), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow() })
export const developmentAssignments = pgTable("development_assignment", { id: text("id").primaryKey(), organizationId: text("organizationId").notNull(), developmentId: text("developmentId").notNull(), memberId: text("memberId").notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow() })
export const developmentComments = pgTable("development_comment", { id: text("id").primaryKey(), developmentId: text("developmentId").notNull(), organizationId: text("organizationId").notNull(), authorId: text("authorId").notNull(), body: text("body").notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow() })
export const organizationNotifications = pgTable("organization_notification", { id: text("id").primaryKey(), organizationId: text("organizationId").notNull(), userId: text("userId").notNull(), type: text("type").notNull(), title: text("title").notNull(), body: text("body").notNull(), readAt: timestamp("readAt", { withTimezone: true }), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow() })
export const manualVersions = pgTable("manual_version", { id: text("id").primaryKey(), developmentId: text("developmentId").notNull(), organizationId: text("organizationId").notNull(), manualType: text("manualType").notNull(), revision: integer("revision").notNull(), status: text("status").notNull().default("rascunho"), comment: text("comment"), filename: text("filename").notNull(), pathname: text("pathname").notNull(), sections: integer("sections").notNull().default(0), pages: integer("pages").notNull().default(0), attachments: integer("attachments").notNull().default(0), finishingTableId: text("finishingTableId"), finishingRevision: integer("finishingRevision"), finishingRows: integer("finishingRows").notNull().default(0), createdBy: text("createdBy").notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow() })
export const finishingTables = pgTable("finishing_table", { id: text("id").primaryKey(), developmentId: text("developmentId").notNull(), organizationId: text("organizationId").notNull(), tower: text("tower").notNull().default(""), typology: text("typology").notNull(), unitModel: text("unitModel").notNull(), area: text("area").notNull(), revision: integer("revision").notNull().default(1), status: text("status").notNull().default("rascunho"), data: jsonb("data").notNull().default({}), lastEditorId: text("lastEditorId").notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull().defaultNow(), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow() })
export const finishingTableHistory = pgTable("finishing_table_history", { id: text("id").primaryKey(), finishingTableId: text("finishingTableId").notNull(), developmentId: text("developmentId").notNull(), organizationId: text("organizationId").notNull(), revision: integer("revision").notNull(), status: text("status").notNull(), data: jsonb("data").notNull().default({}), changedBy: text("changedBy").notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow() })
