// Gerado a partir de data/Checklist_inicial_BASE — categorias e itens reais
import type { ChecklistItem } from "@/lib/mock-data"

export const checklistCategories: string[] = [
  "Sistema de Coberturas",
  "Sistema de Fundação",
  "Sistema de Vedação",
  "Mobiliário",
  "Sistema de Esquadrias",
  "Sistema de Pisos",
  "Estrutura",
  "Instalações Hidráulicas",
  "Área Comum",
  "Instalações Elétricas",
  "Sistema de Prevenção e Combate a Incêndio",
  "Sistema de Impermeabilização",
  "Sistema de Instalação de Gás",
  "Sistema de Climatização",
]

export const checklistItems: ChecklistItem[] = [
  {
    id: "ck-sistem-forro-de-gesso",
    category: "Sistema de Coberturas",
    item: "Forro de gesso",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-sistem-forro-de-madeira",
    category: "Sistema de Coberturas",
    item: "Forro de madeira",
    scope: "comum",
    status: "possui",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-sistem-forro-em-pvc",
    category: "Sistema de Coberturas",
    item: "Forro em PVC",
    scope: "comum",
    status: "em_andamento",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-sistem-ponto-de-ancoragem",
    category: "Sistema de Coberturas",
    item: "Ponto de ancoragem",
    scope: "comum",
    status: "nao_aplicado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-sistem-laje-plana",
    category: "Sistema de Coberturas",
    item: "Laje plana",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-sistem-telha-metalica",
    category: "Sistema de Coberturas",
    item: "Telha metálica",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-sistem-telha-pvc",
    category: "Sistema de Coberturas",
    item: "Telha PVC",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-sistem-engradamento-metalico",
    category: "Sistema de Coberturas",
    item: "Engradamento metálico",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-sistem-telha-metalica-1",
    category: "Sistema de Coberturas",
    item: "Telha metálica",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-sistem-bloco-de-fundacao",
    category: "Sistema de Fundação",
    item: "Bloco de fundação",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 6118"],
  },
  {
    id: "ck-sistem-radier",
    category: "Sistema de Fundação",
    item: "Radier",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 6118"],
  },
  {
    id: "ck-sistem-viga-de-fundacao",
    category: "Sistema de Fundação",
    item: "Viga de fundação",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 6118"],
  },
  {
    id: "ck-sistem-fundacoes-profundas",
    category: "Sistema de Fundação",
    item: "Fundações profundas",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 6118"],
  },
  {
    id: "ck-sistem-estacas",
    category: "Sistema de Fundação",
    item: "Estacas",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 6118"],
  },
  {
    id: "ck-sistem-bloco-ceramico",
    category: "Sistema de Vedação",
    item: "Bloco cerâmico",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575-4"],
  },
  {
    id: "ck-sistem-bloco-de-concreto",
    category: "Sistema de Vedação",
    item: "Bloco de concreto",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575-4"],
  },
  {
    id: "ck-sistem-parede-em-gesso-acartonado-drywall",
    category: "Sistema de Vedação",
    item: "Parede em gesso acartonado (drywall)",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575-4"],
  },
  {
    id: "ck-sistem-revestimentos-ceramico",
    category: "Sistema de Vedação",
    item: "Revestimentos cerâmico",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575-4"],
  },
  {
    id: "ck-sistem-pedras-naturais",
    category: "Sistema de Vedação",
    item: "Pedras naturais",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575-4"],
  },
  {
    id: "ck-sistem-pintura",
    category: "Sistema de Vedação",
    item: "Pintura",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "01 - Orientar que não entregamos a parede prepara para instalação de papel de parede, para isso deve-se realizar a aplicação de uma demão de tinta acrílica para que quando aplicado a cola de papel de parede tenha a devida aderência com o local de aplicação.",
    obsSindico: "",
    norms: ["NBR 15575-4"],
  },
  {
    id: "ck-sistem-papel-de-parede",
    category: "Sistema de Vedação",
    item: "Papel de parede",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575-4"],
  },
  {
    id: "ck-mobili-maquina-de-lavar-e-secar-roupa",
    category: "Mobiliário",
    item: "Máquina de Lavar e Secar Roupa",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-mobili-maquina-de-secar-roupa",
    category: "Mobiliário",
    item: "Máquina de Secar Roupa",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-mobili-fogao-a-gas",
    category: "Mobiliário",
    item: "Fogão a gás",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-mobili-cooktop-por-inducao-sem-ponto-de-gas",
    category: "Mobiliário",
    item: "Cooktop por indução (sem ponto de gás)",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-mobili-cozinha-area-de-servico-e-banheiros",
    category: "Mobiliário",
    item: "Cozinha, Área de Serviço e Banheiros",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "01 - Orientação para conferência das medidas dos locais a serem instalados os equipamentos, a fim de evitar compra indevida devido a falta de espaço\n02 - Orientação para as tomadas dos equipamentos, devido as diferentes capacidades e circuitos\n03 - Prospectar a projeção de coifa ou depurador, caso seja entregue pelo empreendimento\n04 - Orientação quanto a utilização da redução adequada ao instalar a máquina de lavar roupas ou louças, garantindo a conexão correta com a tubulação",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-mobili-micro-ondas",
    category: "Mobiliário",
    item: "Micro-ondas",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-mobili-forno-eletrico",
    category: "Mobiliário",
    item: "Forno elétrico",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-mobili-depurador",
    category: "Mobiliário",
    item: "Depurador",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-mobili-chuveiro-eletrico",
    category: "Mobiliário",
    item: "Chuveiro elétrico",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-mobili-espera-para-varal-de-teto",
    category: "Mobiliário",
    item: "Espera para varal de teto",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-mobili-local-para-instalacao-de-box-de-banheiro",
    category: "Mobiliário",
    item: "Local para instalação de box de banheiro (filete)",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-mobili-marmore-sintetico-bancadas-e-tanques",
    category: "Mobiliário",
    item: "Mármore sintético (bancadas e tanques)",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-mobili-mobiliario-planejado",
    category: "Mobiliário",
    item: "Mobiliário planejado",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: [],
  },
  {
    id: "ck-sistem-esquadria-caixilho-de-madeira",
    category: "Sistema de Esquadrias",
    item: "Esquadria / Caixilho de madeira",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 10821","NBR 7199"],
  },
  {
    id: "ck-sistem-mdf",
    category: "Sistema de Esquadrias",
    item: "MDF",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 10821","NBR 7199"],
  },
  {
    id: "ck-sistem-porta-pronta",
    category: "Sistema de Esquadrias",
    item: "Porta pronta",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 10821","NBR 7199"],
  },
  {
    id: "ck-sistem-esquadria-caixilho-em-aluminio",
    category: "Sistema de Esquadrias",
    item: "Esquadria / Caixilho em alumínio",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 10821","NBR 7199"],
  },
  {
    id: "ck-sistem-persiana-integrada",
    category: "Sistema de Esquadrias",
    item: "Persiana integrada",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "01 - Marca do motor entregue\n02 - Voltagem do motor\n03 - Modelo do controle da persiana\n04 - Empresa responsável pela instalação",
    obsSindico: "",
    norms: ["NBR 10821","NBR 7199"],
  },
  {
    id: "ck-sistem-vidro-comum",
    category: "Sistema de Esquadrias",
    item: "Vidro comum",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 10821","NBR 7199"],
  },
  {
    id: "ck-sistem-vidro-miniboreal",
    category: "Sistema de Esquadrias",
    item: "Vidro miniboreal",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 10821","NBR 7199"],
  },
  {
    id: "ck-sistem-vidro-laminado",
    category: "Sistema de Esquadrias",
    item: "Vidro laminado",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 10821","NBR 7199"],
  },
  {
    id: "ck-sistem-fechadura-eletronica",
    category: "Sistema de Esquadrias",
    item: "Fechadura eletrônica",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "01 - Informações de configuração do modelo da fechadura, caso seja entregue com fechadura eletrônica",
    obsSindico: "",
    norms: ["NBR 10821","NBR 7199"],
  },
  {
    id: "ck-sistem-pedras-naturais-1",
    category: "Sistema de Pisos",
    item: "Pedras naturais",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13753"],
  },
  {
    id: "ck-sistem-piso-cimentado-natural",
    category: "Sistema de Pisos",
    item: "Piso cimentado natural",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13753"],
  },
  {
    id: "ck-sistem-piso-em-concreto-estruturado",
    category: "Sistema de Pisos",
    item: "Piso em concreto estruturado",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13753"],
  },
  {
    id: "ck-sistem-piso-drenante",
    category: "Sistema de Pisos",
    item: "Piso drenante",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13753"],
  },
  {
    id: "ck-sistem-piso-emborrachado",
    category: "Sistema de Pisos",
    item: "Piso emborrachado",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13753"],
  },
  {
    id: "ck-sistem-piso-em-bloco-de-concreto-intertravado",
    category: "Sistema de Pisos",
    item: "Piso em bloco de concreto intertravado",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13753"],
  },
  {
    id: "ck-sistem-piso-laminado",
    category: "Sistema de Pisos",
    item: "Piso laminado",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13753"],
  },
  {
    id: "ck-sistem-piso-vinilico",
    category: "Sistema de Pisos",
    item: "Piso vinílico",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13753"],
  },
  {
    id: "ck-sistem-revestimentos-de-piso",
    category: "Sistema de Pisos",
    item: "Revestimentos de piso",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13753"],
  },
  {
    id: "ck-sistem-carpete",
    category: "Sistema de Pisos",
    item: "Carpete",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13753"],
  },
  {
    id: "ck-estrut-concreto-armado",
    category: "Estrutura",
    item: "Concreto armado",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 6118","NBR 15575-2"],
  },
  {
    id: "ck-estrut-paredes-de-concreto",
    category: "Estrutura",
    item: "Paredes de concreto",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 6118","NBR 15575-2"],
  },
  {
    id: "ck-estrut-alvenaria-estrutural",
    category: "Estrutura",
    item: "Alvenaria estrutural",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 6118","NBR 15575-2"],
  },
  {
    id: "ck-estrut-estrutura-metalica",
    category: "Estrutura",
    item: "Estrutura metálica",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 6118","NBR 15575-2"],
  },
  {
    id: "ck-instal-sistema-hidrossanitario",
    category: "Instalações Hidráulicas",
    item: "Sistema Hidrossanitário",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "01 - Separar a página de instalação de gás e exaustão de instalação hidráulica\n02 - Localização do encaminhamento das tubulações de água quente, fria e esgoto.\n03 - Incluir a projeção de sanca e forro com o adendo de não perfuração\n04 - Incluir vistas de todas as paredes que contém tubulação hidráulica\n05 - Sinalizar shafts que não devem ser perfurados.\n06 - Orientar que na instalação de flexível no sistema pex não deve-se utilizar veda rosca, o próprio flexível de pex contem um anel de vedação para estancar.",
    obsSindico: "",
    norms: ["NBR 5626","NBR 8160"],
  },
  {
    id: "ck-instal-pressurizacao-de-escadas",
    category: "Instalações Hidráulicas",
    item: "Pressurização de escadas",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Tabela de informações contendo: Marca do motor e potência",
    norms: ["NBR 5626","NBR 8160"],
  },
  {
    id: "ck-instal-reuso-de-agua-pluvial",
    category: "Instalações Hidráulicas",
    item: "Reúso de água pluvial",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 5626","NBR 8160"],
  },
  {
    id: "ck-instal-bombas-de-reuso",
    category: "Instalações Hidráulicas",
    item: "Bombas de reuso",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Tabela de informações sobre o sistema entregue pela construtora, contendo:\n02 - Marca da bomba\n03 - Potencia e força manométrica\n04 - Quantidade",
    norms: ["NBR 5626","NBR 8160"],
  },
  {
    id: "ck-instal-valvulas-estacoes-redutoras-de-pressao",
    category: "Instalações Hidráulicas",
    item: "Válvulas / estações redutoras de pressão",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Menção a localização das válvulas redutoras de pressão\n02 - Marca das válvulas\n03 - Empresa responsável pela instalação\n04 - Orientações quanto a manutenção periódica",
    norms: ["NBR 5626","NBR 8160"],
  },
  {
    id: "ck-instal-caixa-de-retencao-de-agua-pluvial",
    category: "Instalações Hidráulicas",
    item: "Caixa de retenção de água pluvial",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 5626","NBR 8160"],
  },
  {
    id: "ck-instal-medidor-de-consumo-de-agua",
    category: "Instalações Hidráulicas",
    item: "Medidor de consumo de água",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "01 - Especificar se será entregue com o medidor ou se será apenas previsto",
    obsSindico: "",
    norms: ["NBR 5626","NBR 8160"],
  },
  {
    id: "ck-instal-metais-para-acabamentos",
    category: "Instalações Hidráulicas",
    item: "Metais para acabamentos",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "01 - Constar registros instalados nos apartamentos (pressão ou gaveta)\n02 - Diâmetro do registro\n03 - Marca do registro\n04 - Acabamentos do registro\n05 - Elaboração de tabela por ambiente",
    obsSindico: "",
    norms: ["NBR 5626","NBR 8160"],
  },
  {
    id: "ck-instal-bombas-de-pressurizacao",
    category: "Instalações Hidráulicas",
    item: "Bombas de pressurização",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Tabela de informações sobre o sistema entregue pela construtora, contendo:\n02 - Marca da bomba\n03 -Potencia e força manométrica\n04 - Quantidade",
    norms: ["NBR 5626","NBR 8160"],
  },
  {
    id: "ck-instal-bombas-de-recalque",
    category: "Instalações Hidráulicas",
    item: "Bombas de recalque",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Tabela de informações sobre o sistema entregue pela construtora, contendo:\n02 - Marca da bomba\n03 - Potencia e força manométrica\n04 - Quantidade",
    norms: ["NBR 5626","NBR 8160"],
  },
  {
    id: "ck-instal-reservatorio-inferior",
    category: "Instalações Hidráulicas",
    item: "Reservatório inferior",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Localização dos reservatório\n02 - Capacidade de uso\n03 - Capacidade da reserva de incêndio\n04 - Instrução quanto o abastecimento",
    norms: ["NBR 5626","NBR 8160"],
  },
  {
    id: "ck-instal-reservatorio-superior",
    category: "Instalações Hidráulicas",
    item: "Reservatório superior",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Localização dos reservatório\n02 - Capacidade de uso\n03 - Capacidade da reserva de incêndio\n04 - Instrução quanto o abastecimento",
    norms: ["NBR 5626","NBR 8160"],
  },
  {
    id: "ck-area-c-acessibilidade",
    category: "Área Comum",
    item: "Acessibilidade",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-piso-podotatil",
    category: "Área Comum",
    item: "Piso podotátil",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-rampa-pne",
    category: "Área Comum",
    item: "Rampa PNE",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-sinalizacao-braile",
    category: "Área Comum",
    item: "Sinalização braile",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-sanitarios-pne",
    category: "Área Comum",
    item: "Sanitários PNE",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-alarme-de-emergencia-em-sanitarios-pne",
    category: "Área Comum",
    item: "Alarme de emergência em sanitários PNE",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-area-de-resgate-pne",
    category: "Área Comum",
    item: "Área de resgate PNE",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-elevador-de-acessibilidade-para-piscinas",
    category: "Área Comum",
    item: "Elevador de acessibilidade para piscinas",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-acessos-automatizados",
    category: "Área Comum",
    item: "Acessos automatizados",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-portas-para-pedestres",
    category: "Área Comum",
    item: "Portas para pedestres",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-leitor-digital",
    category: "Área Comum",
    item: "Leitor digital",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-portoes-para-veiculos",
    category: "Área Comum",
    item: "Portões para veículos",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-sensor-iva-antiesmagamento",
    category: "Área Comum",
    item: "Sensor IVA antiesmagamento",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-circulacao-vertical",
    category: "Área Comum",
    item: "Circulação vertical",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-elevador",
    category: "Área Comum",
    item: "Elevador",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-plataforma-elevatoria",
    category: "Área Comum",
    item: "Plataforma elevatória",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-playground",
    category: "Área Comum",
    item: "Playground",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-espaco-kids",
    category: "Área Comum",
    item: "Espaço kids",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-fitness-academia",
    category: "Área Comum",
    item: "Fitness / academia",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-gerador-de-energia",
    category: "Área Comum",
    item: "Gerador de energia",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Tabela de informações sobre o sistema entregue pela construtora, contendo:\n02 - Marca do equipamento\n03 - Capacidade de autonomia\n04 - Quantidade de armazenamento do tanque de combustível\n05 - Combustível a ser utilizado\n06 - Menção ao botão de acionamento alocado na portaria",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-piscinas",
    category: "Área Comum",
    item: "Piscinas",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Marca do revestimento e rejunte utilizado nas piscinas adulta e infantil\n02 - Capacidade em litros da piscina adulta e infantil\n03 - Descrever sobre o botão de emergencia localizado na area da piscina",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-quadra-de-beach-tenis",
    category: "Área Comum",
    item: "Quadra de beach tênis",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-sistema-de-seguranca",
    category: "Área Comum",
    item: "Sistema de Segurança",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-cerca-eletrica",
    category: "Área Comum",
    item: "Cerca elétrica",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-sistema-de-presenca",
    category: "Área Comum",
    item: "Sistema de presença",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-sistema-de-sonorizacao",
    category: "Área Comum",
    item: "Sistema de sonorização",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-iluminacao-automatica",
    category: "Área Comum",
    item: "Iluminação automática",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-sensor-de-presenca",
    category: "Área Comum",
    item: "Sensor de presença",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-paisagismo-e-irrigacao",
    category: "Área Comum",
    item: "Paisagismo e irrigação",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-junta-de-dilatacao",
    category: "Área Comum",
    item: "Junta de dilatação",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-climatizacao-de-piscinas",
    category: "Área Comum",
    item: "Climatização de piscinas",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Menção ao sistema de climatização das piscinas\n02 - Empresa responsável pela instalação\n03 - Informação quanto ao sistema de alimentação (solar ou a gás)\n04 - Instrução referente ao funcionamento do sistema\n05 - Marca das bombas e filtros instalados",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-elementos-em-aco-inoxidavel",
    category: "Área Comum",
    item: "Elementos em aço inoxidável",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-espelhos",
    category: "Área Comum",
    item: "Espelhos",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-pecas-em-madeira",
    category: "Área Comum",
    item: "Peças em madeira",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-sistema-fotovoltaico",
    category: "Área Comum",
    item: "Sistema fotovoltáico",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Empresa responsável pela instalação\n02 - Tabela de informações sobre o sistema entregue pela construtora, contendo:\n03 - Capacidade das placas\n04 - Potência\n05 - Tipo de sistema (inversor ou micro inversor",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-area-c-sistema-de-carregamento-de-carro-ou-bici",
    category: "Área Comum",
    item: "Sistema de carregamento de carro ou bicicleta",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Menção a entrega do sistema compartilhado de carregamento\n02 - Tipo de carregar\n03 - Capacidade\n04 - Localização do sistema",
    norms: ["NBR 15575"],
  },
  {
    id: "ck-instal-sistema-eletrico",
    category: "Instalações Elétricas",
    item: "Sistema elétrico",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "01 - Incluir a numeração dos circuitos nas tomadas representadas na planta, cozinha, area de serviço, sala, quartos, varandas e banheiros.\n02 - Localização de rabicho nos forros representados com uma lâmpada para localização do cliente onde instalar luminárias.\n03 - Incluir a tabela do diagrama do quadro disjuntor para verificação dos circuitos.\n04 - Separar uma página para sistema de interfonia e tv dos sistemas elétricos de tomada e luz.\n05 - Incluir categoria de entrada de energia dos apartamentos para a solicitação de energia na CPFL\n06 - Incluir um passo a passo das principais informações para solicitar a ligação de energia no site da CPFL",
    obsSindico: "Menção a voltagem das tomadas da área comum",
    norms: ["NBR 5410"],
  },
  {
    id: "ck-instal-sistema-de-protecao-contra-descargas-atm",
    category: "Instalações Elétricas",
    item: "Sistema de Proteção contra Descargas Atmosféricas",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "01 - Especificar se é do tipo Gaiola de Faraday ou Mastro tipo Franklin",
    obsSindico: "",
    norms: ["NBR 5410"],
  },
  {
    id: "ck-instal-sistema-de-telecomunicacoes",
    category: "Instalações Elétricas",
    item: "Sistema de Telecomunicações",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 5410"],
  },
  {
    id: "ck-instal-antena-coletiva-de-tv",
    category: "Instalações Elétricas",
    item: "Antena coletiva de TV",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 5410"],
  },
  {
    id: "ck-instal-cabeamento-estruturado",
    category: "Instalações Elétricas",
    item: "Cabeamento estruturado",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 5410"],
  },
  {
    id: "ck-instal-interfonia",
    category: "Instalações Elétricas",
    item: "Interfonia",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "01 - Separar uma página de projetos para sistema de interfonia e tv dos sistemas elétricos de tomada e luz.",
    obsSindico: "",
    norms: ["NBR 5410"],
  },
  {
    id: "ck-instal-telefonia",
    category: "Instalações Elétricas",
    item: "Telefonia",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 5410"],
  },
  {
    id: "ck-instal-cftv",
    category: "Instalações Elétricas",
    item: "CFTV",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 5410"],
  },
  {
    id: "ck-sistem-alarme-de-emergencia",
    category: "Sistema de Prevenção e Combate a Incêndio",
    item: "Alarme de emergência",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13714"],
  },
  {
    id: "ck-sistem-botoeira-de-emergencia",
    category: "Sistema de Prevenção e Combate a Incêndio",
    item: "Botoeira de emergência",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13714"],
  },
  {
    id: "ck-sistem-central-de-alarme-de-incendio",
    category: "Sistema de Prevenção e Combate a Incêndio",
    item: "Central de alarme de incêndio",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13714"],
  },
  {
    id: "ck-sistem-extintor",
    category: "Sistema de Prevenção e Combate a Incêndio",
    item: "Extintor",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13714"],
  },
  {
    id: "ck-sistem-hidrante",
    category: "Sistema de Prevenção e Combate a Incêndio",
    item: "Hidrante",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13714"],
  },
  {
    id: "ck-sistem-luminaria-de-emergencia",
    category: "Sistema de Prevenção e Combate a Incêndio",
    item: "Luminária de emergência",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13714"],
  },
  {
    id: "ck-sistem-porta-corta-fogo",
    category: "Sistema de Prevenção e Combate a Incêndio",
    item: "Porta corta-fogo",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 13714"],
  },
  {
    id: "ck-sistem-bomba-de-incendio",
    category: "Sistema de Prevenção e Combate a Incêndio",
    item: "Bomba de incêndio",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "01 - Tabela de informações sobre o sistema entregue pela construtora contendo :\n02 - Marca da bomba\n03 - Potência e força manométrica\n04 - Quantidade de bombas",
    norms: ["NBR 13714"],
  },
  {
    id: "ck-sistem-argamassa-polimerica-flexivel",
    category: "Sistema de Impermeabilização",
    item: "Argamassa polimérica flexível",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 9575"],
  },
  {
    id: "ck-sistem-argamassa-polimerica-rigida",
    category: "Sistema de Impermeabilização",
    item: "Argamassa polimérica rígida",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 9575"],
  },
  {
    id: "ck-sistem-manta-asfaltica",
    category: "Sistema de Impermeabilização",
    item: "Manta asfaltica",
    scope: "comum",
    status: "nao_especificado",
    obsProprietario: "",
    obsSindico: "",
    norms: ["NBR 9575"],
  },
  {
    id: "ck-sistem-instalacao-de-gas",
    category: "Sistema de Instalação de Gás",
    item: "Instalação de gás",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "01 - Especificar o tipo de gás que será utilizado\n02 - Sempre consultar a equipe obra se na cozinha sera preparação para instalação de depurador ou coifa\n03 - Inserir encaminhamento de duto deixado no forro para instalação de coifa e onde fica em espera. Sinalizando com um simbolo na planta.\n04 - Sinalizar na planta os locais onde passam as tubulações de gás com rachuras no contrapiso\n05 - Incluir nota sobre a necessidade de atenção quanto a retirada de parede por conta da norma de gás, caso o apartamento seja estúdio",
    obsSindico: "",
    norms: ["NBR 13103","NBR 15526"],
  },
  {
    id: "ck-sistem-medidor-de-consumo-de-gas",
    category: "Sistema de Instalação de Gás",
    item: "Medidor de consumo de gás",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "01 - Especificar se será entregue instalado ou se haverá apenas a previsão",
    obsSindico: "",
    norms: ["NBR 13103","NBR 15526"],
  },
  {
    id: "ck-sistem-ar-condicionado",
    category: "Sistema de Climatização",
    item: "Ar condicionado",
    scope: "unidade",
    status: "nao_especificado",
    obsProprietario: "01 - Vista de drenos de todas as paredes que contém ponto de ar condicionado\n02 - Localização de encaminhamento de tubulação frigorigena pelos forro ou sancas\n03 - Vista de \"área segura\" para perfuração da parede quando temos drenos\n04 - Localização de passantes na estrutura para instalação posterior de tubulação frigorigena, caso o cliente não tenha optado pelo personaliza\n05. Tabela de BTU por ambiente",
    obsSindico: "Tabela de ambientes com as tipologias de ar condicionado com a capacidade de BTU e voltagem",
    norms: ["NBR 16401"],
  },
]
