const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')

module.exports = async function runDatabookTests({ page, admin, editor, outsider, anonymous, dev, origin, directory }) {
  const endpoint = '/api/databook/upload'
  const query = '/api/databook/folders?' + new URLSearchParams({ developmentId: dev })
  async function catalog(context = admin) {
    const response = await context.get(query)
    assert.equal(response.status(), 200, await response.text())
    return response.json()
  }
  assert.equal((await anonymous.get(query)).status(), 401)
  assert.equal((await outsider.get(query)).status(), 404)
  assert.equal((await outsider.post(endpoint, { data: { action: 'prepare', developmentId: dev, name: 'intruso.pdf', contentType: 'application/pdf', size: 10 } })).status(), 404)
  assert.equal((await admin.post(endpoint, { data: { action: 'prepare', developmentId: dev, name: 'vazio.pdf', contentType: 'application/pdf', size: 0 } })).status(), 400)
  assert.equal((await admin.post(endpoint, { data: { action: 'prepare', developmentId: dev, name: 'grande.pdf', contentType: 'application/pdf', size: 50 * 1024 * 1024 + 1 } })).status(), 413)
  const nativeDialogs = []
  const nativeDialog = dialog => { nativeDialogs.push(dialog.type()); void dialog.dismiss() }
  page.on('dialog', nativeDialog)
  try {
    await page.goto(origin + '/empreendimentos/' + dev + '?modulo=databook')
    await page.getByRole('heading', { name: 'DATABOOK', exact: true }).waitFor()
    await page.getByRole('button', { name: 'Nova pasta', exact: true }).waitFor()
    assert.equal(await page.getByLabel('Pasta do upload').count(), 0)
    assert.equal(await page.getByRole('heading', { name: 'Todos os arquivos', exact: true }).count(), 0)
    await page.getByRole('button', { name: 'Nova pasta', exact: true }).click()
    await page.getByRole('dialog').getByLabel('Nome da pasta', { exact: true }).fill('Documentos da unidade')
    await page.getByRole('dialog').getByRole('button', { name: 'Criar pasta', exact: true }).click()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    let data = await catalog()
    const folder = data.folders.find(item => item.name === 'Documentos da unidade')
    assert.ok(folder)
    await page.reload()
    const folderNavigation = page.getByLabel('Pastas do DATABOOK')
    await folderNavigation.getByRole('button', { name: /^Documentos da unidade\s*0$/ }).click()
    await page.getByRole('button', { name: 'Arraste arquivos ou clique para adicionar', exact: true }).getByText('Documentos da unidade', { exact: true }).waitFor()
    const bytes = Buffer.alloc(5 * 1024 * 1024, 65)
    bytes.write('%PDF-1.4\nArquivo de teste isolado\n')
    let failOnce = true
    await page.route('**/api/databook/upload', async route => {
      const request = route.request()
      if (request.headers()['content-type']?.startsWith('application/json')) {
        const body = request.postDataJSON()
        if (body.action === 'prepare' && body.name === 'repetir.pdf' && failOnce) {
          failOnce = false
          return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Falha temporária de teste neste arquivo.' }) })
        }
      }
      return route.continue()
    })
    await page.getByLabel('Arquivos do DATABOOK').setInputFiles([
      { name: 'arquivo-5mb.pdf', mimeType: 'application/pdf', buffer: bytes },
      { name: 'repetir.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-arquivo-repetir') },
    ])
    await page.getByRole('link', { name: 'Baixar arquivo arquivo-5mb.pdf', exact: true }).waitFor()
    const retryJob = page.getByLabel('Envios de arquivos').locator('li').filter({ hasText: 'repetir.pdf' })
    await retryJob.getByRole('alert').filter({ hasText: 'Falha temporária' }).waitFor()
    data = await catalog()
    assert.equal(data.files.length, 1, 'Partial failure preserves successful upload')
    assert.equal(data.files[0].folder, folder.name)
    assert.equal(data.files[0].sizeBytes, bytes.length)
    const download = await admin.get('/api/databook/file?pathname=' + encodeURIComponent(data.files[0].pathname))
    assert.equal(download.status(), 200)
    assert.equal((await download.body()).length, bytes.length)
    assert.equal((await outsider.get('/api/databook/file?pathname=' + encodeURIComponent(data.files[0].pathname))).status(), 404)
    assert.equal((await anonymous.get('/api/databook/file?pathname=' + encodeURIComponent(data.files[0].pathname))).status(), 401)
    await retryJob.getByRole('button', { name: 'Tentar novamente', exact: true }).click()
    await page.getByRole('link', { name: 'Baixar arquivo repetir.pdf', exact: true }).waitFor()
    await page.unroute('**/api/databook/upload')
    assert.equal((await catalog()).files.length, 2)
    const transfer = await page.evaluateHandle(() => {
      const dataTransfer = new DataTransfer()
      dataTransfer.items.add(new File(['%PDF-arquivo-arrastado'], 'arrastado.pdf', { type: 'application/pdf' }))
      return dataTransfer
    })
    await page.getByRole('button', { name: 'Arraste arquivos ou clique para adicionar', exact: true }).dispatchEvent('drop', { dataTransfer: transfer })
    await transfer.dispose()
    await page.getByRole('link', { name: 'Baixar arquivo arrastado.pdf', exact: true }).waitFor()
    data = await catalog()
    assert.equal(data.files.length, 3)
    assert.equal(data.files.find(file => file.name === 'arrastado.pdf').folder, folder.name)
    // The real API rejects stolen/tampered tickets and registers a retry only once.
    const prepare = await editor.post(endpoint, { data: { action: 'prepare', developmentId: dev, folderId: folder.id, name: 'idempotente.pdf', contentType: 'application/pdf', size: 9 } })
    assert.equal(prepare.status(), 200, await prepare.text())
    const prepared = await prepare.json()
    assert.equal(prepared.transport, 'local')
    assert.equal((await admin.post(endpoint, { data: { action: 'finalize', ticket: prepared.ticket } })).status(), 403)
    assert.equal((await editor.post(endpoint, { data: { action: 'finalize', ticket: prepared.ticket + 'x' } })).status(), 400)
    const upload = await editor.post(endpoint, { multipart: { ticket: prepared.ticket, file: { name: 'idempotente.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-test') } } })
    assert.equal(upload.status(), 200, await upload.text())
    const uploaded = (await upload.json()).file
    const again = await editor.post(endpoint, { data: { action: 'finalize', ticket: prepared.ticket } })
    assert.equal(again.status(), 200, await again.text())
    assert.equal((await again.json()).file.id, uploaded.id)
    assert.equal((await catalog()).files.filter(file => file.pathname === uploaded.pathname).length, 1)
    await page.reload()
    await page.getByLabel('Pastas do DATABOOK').getByRole('button', { name: /^Documentos da unidade\s*4$/ }).click()
    await page.getByRole('button', { name: 'Excluir arquivo arrastado.pdf', exact: true }).click()
    const deletion = page.getByRole('dialog')
    await deletion.getByRole('heading', { name: 'Excluir arquivo', exact: true }).waitFor()
    await deletion.getByRole('button', { name: 'Cancelar', exact: true }).click()
    assert.ok((await catalog()).files.some(file => file.name === 'arrastado.pdf'))
    await page.getByRole('button', { name: 'Excluir arquivo arrastado.pdf', exact: true }).click()
    await page.route('**/api/databook/delete', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Exclusão indisponível no teste.' }) }))
    await deletion.getByRole('button', { name: 'Excluir arquivo', exact: true }).click()
    await deletion.getByRole('alert').filter({ hasText: 'Exclusão indisponível' }).waitFor()
    assert.ok((await catalog()).files.some(file => file.name === 'arrastado.pdf'))
    await page.unroute('**/api/databook/delete')
    await deletion.getByRole('button', { name: 'Excluir arquivo', exact: true }).click()
    await deletion.waitFor({ state: 'hidden' })
    assert.ok(!(await catalog()).files.some(file => file.name === 'arrastado.pdf'))
    await page.getByRole('button', { name: 'Renomear pasta Documentos da unidade', exact: true }).click()
    await page.getByRole('dialog').getByLabel('Nome da pasta', { exact: true }).fill('Acabamentos por unidade')
    await page.getByRole('dialog').getByRole('button', { name: 'Salvar nome', exact: true }).click()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    data = await catalog()
    assert.equal(data.folders.find(item => item.id === folder.id).name, 'Acabamentos por unidade')
    assert.ok(data.files.every(file => file.folder === 'Acabamentos por unidade'))
    await page.screenshot({ path: path.join(directory, 'databook-envios.png') })
    await page.getByRole('button', { name: 'Excluir pasta Acabamentos por unidade', exact: true }).click()
    await page.getByRole('dialog').getByRole('heading', { name: 'Excluir pasta', exact: true }).waitFor()
    await page.screenshot({ path: path.join(directory, 'databook-dialogo-exclusao.png'), animations: 'disabled' })
    await page.getByRole('dialog').getByRole('button', { name: 'Excluir pasta', exact: true }).click()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    data = await catalog()
    assert.ok(!data.folders.some(item => item.id === folder.id))
    assert.equal(data.files.length, 0)
    await page.reload()
    await page.getByRole('button', { name: 'Nova pasta', exact: true }).waitFor()
    assert.ok(!(await catalog()).folders.some(item => item.id === folder.id))
    assert.deepEqual(nativeDialogs, [])
  } finally { page.off('dialog', nativeDialog) }
}
