const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')
const { chromium, request } = require(process.env.PLAYWRIGHT_PACKAGE_PATH || 'playwright')
const { Pool } = require('pg')
const { PDFDocument } = require('pdf-lib')
const { createHash, randomUUID } = require('node:crypto')
const origin = process.env.TEST_BASE_URL || 'http://localhost:3000'
assert.ok(['localhost','127.0.0.1','[::1]'].includes(new URL(origin).hostname), 'Run fixture mutations only against an isolated local application')
assert.ok(process.env.DATABASE_URL && ['localhost','127.0.0.1','[::1]'].includes(new URL(process.env.DATABASE_URL).hostname), 'An isolated local DATABASE_URL is required')
const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const suffix = Date.now().toString(36)
const directory = process.env.TEST_ARTIFACT_DIR || path.join(process.cwd(), 'work', 'composer-test')
const flatten = sections => sections.flatMap(section => [section, ...flatten(section.children)])
const commands = preview => preview.layout.pages.flatMap(page => page.commands).filter(command => command.type === 'text').map(command => command.text).join(' ')
;(async () => {
  await fs.mkdir(directory, { recursive: true })
  const fixtureIp='198.18.'+((Date.now()>>>8)&255)+'.'+(Date.now()&255)
  const extraHTTPHeaders={Origin:origin,'X-Forwarded-For':fixtureIp}
  const admin = await request.newContext({ baseURL: origin, extraHTTPHeaders })
  const reviewer = await request.newContext({ baseURL: origin, extraHTTPHeaders })
  const editor = await request.newContext({ baseURL: origin, extraHTTPHeaders })
  const anonymous = await request.newContext({ baseURL: origin })
  const outsider = await request.newContext({ baseURL: origin, extraHTTPHeaders })
  let browser
  try {
    const org = 'composer-org-'+suffix
    const inviterId = 'composer-inviter-'+suffix
    await pool.query('INSERT INTO organization(id,name,slug) VALUES($1,$2,$3)', [org, 'Construtora São João', org])
    await pool.query('INSERT INTO "user"(id,name,email,"emailVerified") VALUES($1,$2,$3,true)',[inviterId,'Local fixture inviter','inviter-'+suffix+'@example.test'])
    async function signup(context, kind) {
      const data={name:kind+' compositor',email:kind+'-'+suffix+'@example.test',password:'ComposerTest!2026-isolated'}
      const token=randomUUID()
      await pool.query('INSERT INTO organization_invitation(id,"organizationId",name,email,role,"tokenHash","expiresAt","invitedBy") VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[randomUUID(),org,data.name,data.email,'admin',createHash('sha256').update(token).digest('hex'),new Date(Date.now()+3600000),inviterId])
      let result
      for(let attempt=0;attempt<3;attempt++){
        result=await context.post('/api/auth/sign-up/email',{data,headers:{'x-dg-invite':token}})
        if(result.status()!==429)break
        const seconds=Math.min(30,Math.max(1,Number(result.headers()['retry-after'])||11))
        await new Promise(resolve=>setTimeout(resolve,(seconds+1)*1000))
      }
      assert.equal(result.status(), 200, await result.text())
      return (await result.json()).user.id
    }
    const adminId = await signup(admin, 'admin')
    const reviewerId = await signup(reviewer, 'reviewer')
    const editorId = await signup(editor, 'editor')
    const outsiderId = await signup(outsider, 'outsider')
    for(const [id, role] of [[adminId,'admin'],[reviewerId,'admin'],[editorId,'editor']]) await pool.query('INSERT INTO member(id,"organizationId","userId",role,status) VALUES($1,$2,$3,$4,$5)', ['member-'+id,org,id,role,'active'])
    const otherOrg='other-org-'+suffix
    await pool.query('INSERT INTO organization(id,name,slug) VALUES($1,$2,$3)',[otherOrg,'Outra organização',otherOrg])
    await pool.query('INSERT INTO member(id,"organizationId","userId",role,status) VALUES($1,$2,$3,$4,$5)',['member-'+outsiderId,otherOrg,outsiderId,'admin','active'])
    const dev = 'composer-dev-'+suffix
    const item = (id, title, scopes) => ({ id, item: title, category:'Sistemas', scope:scopes[0], scopes, status:'possui', norms:['NBR 5674'], maintenance:[], obsProprietario:'', obsSindico:'' })
    const checklist = [item('approved','Estrutura',['unidade']),item('draft','Pintura',['unidade']),item('waiting','Esquadrias',['unidade']),item('rejected','Impermeabilização',['unidade']),item('shared','Instalações hidráulicas',['unidade','comum']),item('common','Elevadores',['comum'])]
    const task = marker => [{id:'m-'+marker,task:marker,frequency:'Anual',responsible:'Proprietário'}]
    const systems = Object.fromEntries(checklist.filter(item=>item.scopes.includes('unidade')).map(item=>[item.id+'::unidade','<p>PRIVATIVO_'+item.id+'_á ç º — “teste”</p>']))
    const maintenance = Object.fromEntries(checklist.filter(item=>item.scopes.includes('unidade')).map(item=>[item.id+'::unidade',task('MANUTENCAO_'+item.id)]))
    const data = {ficha:{towers:'2',apartments:'20',typologies:'2',areas:'70',completionDate:'2027-01-01'},checklist,schedule:[{id:'stage-1',kind:'ficha',name:'Ficha',weight:100,progress:100}],identity:{displayName:'Residencial São João',primary:'#17324D',secondary:'#B59A70'},manuals:{proprietario:{sistemas:systems,manutencao:maintenance,editorial:{warranties:[{sistema:'Impermeabilização',elemento:'Laje',descricaoFalha:'Infiltração',prazo:'Conforme contrato',condicoes:'Inspeção anual'}]}},sindico:{sistemas:{'shared::comum':'<p>COMUM_HIDRAULICA_aprovada</p>','common::comum':'<p>COMUM_ELEVADORES_aprovados</p>'},manutencao:{'shared::comum':[],'common::comum':[]}}}}
    await pool.query('INSERT INTO development(id,"userId","organizationId",name,client,"deliveryDate",data) VALUES($1,$2,$3,$4,$5,$6,$7)',[dev,adminId,org,'Residencial São João','Construtora São João','2027-01-01',data])
    await pool.query('INSERT INTO development_assignment(id,"organizationId","developmentId","memberId",role) VALUES($1,$2,$3,$4,$5)',['grant-'+suffix,org,dev,'member-'+editorId,'editor'])
    const states = {approved:'aprovado',draft:'rascunho',waiting:'aguardando_validacao',rejected:'reprovado',shared:'aprovado',common:'aprovado'}
    for(const system of checklist) for(const scope of system.scopes) for(const section of ['sistemas','manutencao']) await pool.query('INSERT INTO development_content_validation(id,"developmentId","organizationId","contextKey",section,status,"lastEditorId") VALUES($1,$2,$3,$4,$5,$6,$7)',[`${system.id}-${scope}-${section}-${suffix}`,dev,org,system.id+'::'+scope,section,scope==='comum'?'aprovado':section==='manutencao'&&system.id==='rejected'?'aprovado':section==='manutencao'&&system.id==='approved'?'rascunho':states[system.id],editorId])
    const finishingId = 'finishing-'+suffix
    await pool.query('INSERT INTO finishing_table(id,"developmentId","organizationId",tower,typology,"unitModel",area,status,data,"lastEditorId") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[finishingId,dev,org,'Torre A','Tipologia 01','Apto 101','70','rascunho',{ambientes:[{id:'room',ambiente:'Cozinha',pisoRodapeBancada:'Porcelanato',parede:'Cerâmica',teto:'Gesso'}],materiais:[{id:'material',material:'Piso',aplicacao:'Piso',ambiente:'Cozinha',marca:'FABRICANTE_APROVADO',linha:'Acetinado',referencia:'São João',formato:'60 x 60'}]},editorId])
    const loginTarget='/empreendimentos/'+dev+'?modulo=elaboracao&aba=textos&manual=proprietario&item=approved%3A%3Aunidade&conteudo=manutencao'
    const guestAccess=await anonymous.get(loginTarget,{maxRedirects:0})
    assert.equal(guestAccess.status(),307,await guestAccess.text())
    const loginLocation=new URL(guestAccess.headers().location,origin)
    assert.equal(loginLocation.pathname,'/sign-in')
    assert.equal(loginLocation.searchParams.get('next'),loginTarget)
    assert.equal((await outsider.get(loginTarget,{maxRedirects:0})).status(),404)
    assert.equal((await admin.get('/empreendimentos/missing-development',{maxRedirects:0})).status(),404)
    async function preview(type) { const result = await admin.post('/api/manuals/preview',{data:{developmentId:dev,manualType:type}});assert.equal(result.status(),200,await result.text());return result.json() }
    assert.equal((await anonymous.post('/api/manuals/preview',{data:{developmentId:dev}})).status(),401)
    for(const endpoint of ['preview','compile','editorial']) assert.equal((await outsider.post('/api/manuals/'+endpoint,{data:{developmentId:dev}})).status(),404)
    let unit = await preview('proprietario')
    assert.equal(unit.readiness.ok,false)
    const source = JSON.stringify(unit.document)
    assert.ok(source.includes('PRIVATIVO_approved'));assert.ok(!source.includes('PRIVATIVO_draft'));assert.ok(source.includes('PRIVATIVO_waiting'));assert.ok(!source.includes('PRIVATIVO_rejected'));assert.ok(!source.includes('COMUM_ELEVADORES'));assert.ok(source.includes('MANUTENCAO_rejected'));assert.ok(!source.includes('MANUTENCAO_approved'))
    assert.ok(unit.layout.pages.flatMap(page=>page.commands).some(command=>command.type==='text'&&command.text.includes('PRIVATIVO_waiting')&&command.color==='#B77900'&&command.reviewStatus==='aguardando_validacao'))
    assert.ok(!source.includes('FABRICANTE_APROVADO'));assert.ok(!source.includes('Infiltração'))
    for(const system of ['draft','waiting','rejected'])assert.ok(flatten(unit.document.sections).some(section=>section.id==='sistema-'+system))
    const common = await preview('sindico')
    assert.ok(JSON.stringify(common.document).includes('COMUM_HIDRAULICA'));assert.ok(!JSON.stringify(common.document).includes('PRIVATIVO_'));assert.equal(common.readiness.ok,true)
    assert.equal((await admin.post('/api/manuals/compile',{data:{developmentId:dev,manualType:'proprietario',document:{status:'aprovado'}}})).status(),400)
    assert.equal((await editor.post('/api/manuals/editorial',{data:{developmentId:dev,manualType:'proprietario',action:'save',sectionId:'apresentacao',html:'<p>APRESENTAÇÃO_EDITORIAL_NOVA</p>'}})).status(),200)
    assert.equal((await editor.post('/api/manuals/editorial',{data:{developmentId:dev,manualType:'proprietario',action:'submit',sectionId:'apresentacao'}})).status(),200)
    assert.equal((await editor.post('/api/manuals/editorial',{data:{developmentId:dev,manualType:'proprietario',action:'approve',sectionId:'apresentacao'}})).status(),403)
    const submittedPresentation=await preview('proprietario')
    assert.ok(JSON.stringify(submittedPresentation.document).includes('APRESENTAÇÃO_EDITORIAL_NOVA'))
    assert.ok(submittedPresentation.layout.pages.flatMap(page=>page.commands).some(command=>command.type==='text'&&command.text==='APRESENTAÇÃO_EDITORIAL_NOVA'&&command.color==='#B77900'))
    const approve = await reviewer.post('/api/manuals/editorial',{data:{developmentId:dev,manualType:'proprietario',action:'approve',sectionId:'apresentacao'}});assert.equal(approve.status(),200,await approve.text())
    assert.ok(JSON.stringify((await preview('proprietario')).document).includes('APRESENTAÇÃO_EDITORIAL_NOVA'))
    const warrantySubmit=await editor.post('/api/manuals/editorial',{data:{developmentId:dev,manualType:'proprietario',action:'submit',sectionId:'garantias-tabela'}});assert.equal(warrantySubmit.status(),200,await warrantySubmit.text())
    assert.equal((await reviewer.post('/api/manuals/editorial',{data:{developmentId:dev,manualType:'proprietario',action:'approve',sectionId:'garantias-tabela'}})).status(),200)
    assert.equal((await editor.post('/api/manuals/editorial',{data:{developmentId:dev,manualType:'proprietario',action:'finishing-submit',tableId:finishingId,revision:1}})).status(),200)
    assert.equal((await reviewer.post('/api/manuals/editorial',{data:{developmentId:dev,manualType:'proprietario',action:'finishing-approve',tableId:finishingId,revision:1}})).status(),200)
    assert.ok(!JSON.stringify((await preview('proprietario')).document).includes('FABRICANTE_APROVADO'), 'Finishing tables are independent documents')
    await pool.query('UPDATE development_content_validation SET status=$1 WHERE "developmentId"=$2 AND section IN ($3,$4)',['aprovado',dev,'sistemas','manutencao'])
    unit = await preview('proprietario');assert.equal(unit.readiness.ok,true,JSON.stringify(unit.readiness))
    assert.equal((await admin.post('/api/manuals/compile',{data:{developmentId:dev,manualType:'proprietario',previewFingerprint:'stale'}})).status(),409)
    async function compile(type, snapshot) { const result=await admin.post('/api/manuals/compile',{data:{developmentId:dev,manualType:type,previewFingerprint:snapshot.fingerprint,comment:'Teste de composição'}});assert.equal(result.status(),201,await result.text());const version=await result.json();const download=await admin.get('/api/manuals/file?id='+encodeURIComponent(version.id));assert.equal(download.status(),200);const bytes=await download.body();const pdf=await PDFDocument.load(bytes);assert.equal(pdf.getPageCount(),snapshot.layout.pages.length);await fs.writeFile(path.join(directory,'manual-'+type+'.pdf'),bytes);return version }
    const version = await compile('proprietario',unit)
    await compile('sindico',await preview('sindico'))
    assert.equal((await admin.post('/api/manuals/versions/status',{data:{id:version.id,status:'publicado'}})).status(),400)
    for(const status of ['validacao','aprovado'])assert.equal((await admin.post('/api/manuals/versions/status',{data:{id:version.id,status}})).status(),200)
    const second = await compile('proprietario',await preview('proprietario'))
    for(const status of ['validacao','aprovado'])assert.equal((await admin.post('/api/manuals/versions/status',{data:{id:second.id,status}})).status(),200)
    const simultaneousPublications=await Promise.all([version,second].map(item=>admin.post('/api/manuals/versions/status',{data:{id:item.id,status:'publicado'}})))
    for(const result of simultaneousPublications)assert.equal(result.status(),200,await result.text())
    const history=(await (await admin.get('/api/manuals/versions?developmentId='+dev+'&manualType=proprietario')).json()).versions
    assert.equal(history.length,2);assert.equal(history.filter(item=>item.status==='publicado').length,1);assert.equal(history.filter(item=>item.status==='substituido').length,1);assert.equal(history[0].authorName,'admin compositor')
    await fs.writeFile(path.join(directory,'fixture.json'),JSON.stringify({developmentId:dev,organizationId:org,adminEmail:'admin-'+suffix+'@example.test'}))
    await fs.writeFile(path.join(directory,'auth.json'),JSON.stringify(await admin.storageState()))
    browser=await chromium.launch({headless:true,...(process.env.TEST_BROWSER_EXECUTABLE?{executablePath:process.env.TEST_BROWSER_EXECUTABLE}:{} )})
    const guestContext=await browser.newContext({viewport:{width:1280,height:900}})
    try {
      const guestPage=await guestContext.newPage()
      await guestPage.goto(origin+loginTarget)
      await guestPage.getByRole('heading',{name:'Bem-vindo de volta',exact:true}).waitFor()
      assert.equal(new URL(guestPage.url()).searchParams.get('next'),loginTarget)
      await guestPage.getByLabel('Usuário ou E-mail',{exact:true}).fill('admin-'+suffix+'@example.test')
      await guestPage.getByLabel('Senha',{exact:true}).fill('ComposerTest!2026-isolated')
      await guestPage.getByRole('button',{name:'ENTRAR NA MINHA CONTA',exact:true}).click()
      await guestPage.waitForURL(url=>url.pathname==='/empreendimentos/'+dev&&url.searchParams.get('aba')==='textos'&&url.searchParams.get('conteudo')==='manutencao')
      await guestPage.getByRole('heading',{name:'Textos técnicos',exact:true}).waitFor()
      await guestPage.getByRole('tab',{name:'Manutenção',exact:true}).waitFor()
      assert.equal(await guestPage.getByRole('tab',{name:'Manutenção',exact:true}).getAttribute('aria-selected'),'true')
      assert.equal(new URL(guestPage.url()).searchParams.get('item'),'approved::unidade')
      await guestPage.screenshot({path:path.join(directory,'login-retoma-textos-tecnicos.png')})
      console.log('PREVIEW_LOGIN_PASS: anonymous deep link redirects to login, login restores exact manual/item/maintenance destination, unauthorized tenant and missing development remain 404')
    } finally {await guestContext.close()}
    const context=await browser.newContext({viewport:{width:1600,height:1100},storageState:await admin.storageState()})
    const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message))
    await page.goto(origin+'/empreendimentos/'+dev+'?modulo=emissao')
    await page.getByRole('navigation',{name:'Sumário do manual'}).waitFor()
    await page.locator('[data-manual-page]').first().waitFor()
    assert.equal(await page.getByRole('button',{name:'Editar texto da seção',exact:true}).count(),0)
    assert.equal(await page.getByRole('button',{name:'Enviar para validação',exact:true}).count(),0)
    assert.equal(await page.getByRole('link',{name:'Abrir edição desta seção',exact:true}).count(),0)
    assert.equal(await page.getByLabel('Modo de visualização').locator('option[value="double"]').count(),0)
    assert.equal(await page.getByText(/Os estados indicam a revisão do conteúdo/).count(),0)
    assert.equal(await page.getByRole('button',{name:'Modo edição',exact:true}).count(),1)
    assert.equal(await page.getByRole('button',{name:'Gerar PDF',exact:true}).count(),1)
    await page.getByLabel('Modo de visualização').selectOption('continuous')
    const expectedPageCount=(await preview('proprietario')).layout.pages.length
    await page.waitForFunction(expected=>document.querySelectorAll('[data-manual-page]').length===expected,expectedPageCount)
    assert.equal(await page.locator('[data-manual-page]').count(),expectedPageCount)
    await page.getByRole('button',{name:'Expandir Sistemas Construtivos, Uso e Manutenção',exact:true}).click()
    await page.getByRole('button',{name:/4\.1 Estrutura/}).click()
    const structureHeading=page.locator('[data-manual-page] svg text[font-family$="-heading"]').filter({hasText:/^4\.1 Estrutura$/}).last()
    const assertHeadingVisible=async()=>{
      await page.waitForFunction(()=>{
        const heading=[...document.querySelectorAll('[data-manual-page] svg text[font-family$="-heading"]')].find(node=>node.textContent==='4.1 Estrutura')
        const viewport=document.querySelector('[aria-label="Pré-visualização do manual em páginas A4"]')
        if(!heading||!viewport)return false
        const box=heading.getBoundingClientRect(),frame=viewport.getBoundingClientRect()
        return box.top>=frame.top&&box.bottom<=frame.bottom
      })
      assert.ok(await structureHeading.isVisible())
    }
    await assertHeadingVisible()
    assert.ok(await page.getByRole('button',{name:/4\.1 Estrutura/}).getAttribute('aria-current'))
    await page.getByLabel('Buscar no manual').fill('PRIVATIVO_approved')
    await page.getByText(/resultado/,{exact:false}).waitFor()
    await page.getByLabel('Buscar no manual').fill('')
    await page.getByRole('button',{name:'Aumentar zoom',exact:true}).click()
    await assertHeadingVisible()
    await page.screenshot({path:path.join(directory,'compositor-proprietario.png')})
    await page.getByRole('button',{name:'Histórico',exact:true}).click()
    await page.getByRole('dialog').waitFor();await page.getByText('Substituído',{exact:true}).waitFor();await page.keyboard.press('Escape')
    const commonResponse=page.waitForResponse(response=>response.url().endsWith('/api/manuals/preview')&&response.request().postDataJSON()?.manualType==='sindico'&&response.status()===200)
    await page.getByLabel('Tipo de manual').selectOption('sindico')
    await commonResponse
    await page.getByRole('navigation',{name:'Sumário do manual'}).waitFor()
    await page.waitForFunction(()=>[...document.querySelectorAll('[data-manual-page] svg')].map(svg=>svg.textContent).join(' ').includes('COMUM_HIDRAULICA'))
    assert.ok((await page.locator('svg').allTextContents()).join(' ').includes('COMUM_HIDRAULICA'))
    assert.ok(!(await page.locator('svg').allTextContents()).join(' ').includes('PRIVATIVO_'))
    await page.screenshot({path:path.join(directory,'compositor-sindico.png')})
    const ownerResponse=page.waitForResponse(response=>response.url().endsWith('/api/manuals/preview')&&response.request().postDataJSON()?.manualType==='proprietario'&&response.status()===200)
    await page.getByLabel('Tipo de manual').selectOption('proprietario');await ownerResponse
    await page.getByRole('button',{name:'Visualizar',exact:true}).waitFor()
    await page.getByRole('button',{name:'Modo edição',exact:true}).click()
    await page.getByRole('button',{name:'Expandir Introdução',exact:true}).click()
    await page.getByRole('button',{name:/1\.1 Finalidade do Manual/}).click()
    await page.getByRole('heading',{name:'Textos técnicos',exact:true}).waitFor()
    assert.equal(new URL(page.url()).searchParams.get('aba'),'textos')
    assert.equal(new URL(page.url()).searchParams.get('secao'),'finalidade')
    await page.locator('.tiptap[contenteditable="true"]').fill('FINALIDADE_EDITADA_NA_ELABORACAO')
    await page.getByRole('button',{name:'Salvar texto',exact:true}).click()
    await page.getByRole('status').filter({hasText:'Texto salvo.'}).waitFor()
    assert.equal(await page.locator('.tiptap').innerText(),'FINALIDADE_EDITADA_NA_ELABORACAO')
    assert.equal(await page.getByText('Alterações ainda não salvas',{exact:true}).count(),0)
    await page.getByRole('button',{name:'Enviar para validação',exact:true}).click()
    await page.getByRole('status').filter({hasText:'Conteúdo enviado para validação.'}).waitFor()
    assert.equal(new URL(page.url()).searchParams.get('manual'),'proprietario')
    await page.getByLabel('Tipo de manual dos textos').selectOption('sindico')
    await page.locator('.tiptap[contenteditable="true"]').waitFor()
    assert.ok(!(await page.locator('.tiptap').innerText()).includes('FINALIDADE_EDITADA_NA_ELABORACAO'))
    await page.getByLabel('Tipo de manual dos textos').selectOption('proprietario')
    await page.locator('.tiptap').filter({hasText:'FINALIDADE_EDITADA_NA_ELABORACAO'}).waitFor()
    await page.getByRole('link',{name:'Visualizar no manual',exact:true}).click()
    await page.getByRole('navigation',{name:'Sumário do manual'}).waitFor()
    await page.waitForFunction(()=>[...document.querySelectorAll('[data-manual-page] svg text')].some(node=>node.textContent==='FINALIDADE_EDITADA_NA_ELABORACAO'&&node.getAttribute('fill')==='#B77900'))
    assert.equal(await page.getByRole('button',{name:'Gerar PDF',exact:true}).isDisabled(),true)
    await page.screenshot({path:path.join(directory,'preview-validacao-amarelo.png')})
    await page.getByRole('button',{name:'Modo edição',exact:true}).click()
    await page.getByRole('link',{name:'Editar na Elaboração: FINALIDADE_EDITADA_NA_ELABORACAO',exact:true}).click()
    await page.getByRole('heading',{name:'Textos técnicos',exact:true}).waitFor()
    assert.equal(new URL(page.url()).searchParams.get('secao'),'finalidade')
    const reviewed=await reviewer.post('/api/manuals/editorial',{data:{developmentId:dev,manualType:'proprietario',action:'approve',sectionId:'finalidade'}})
    assert.equal(reviewed.status(),200,await reviewed.text())
    await page.getByRole('link',{name:'Visualizar no manual',exact:true}).click()
    await page.getByRole('navigation',{name:'Sumário do manual'}).waitFor()
    await page.waitForFunction(()=>[...document.querySelectorAll('[data-manual-page] svg text')].some(node=>node.textContent==='FINALIDADE_EDITADA_NA_ELABORACAO'&&node.getAttribute('fill')!=='#B77900'))
    const generation=page.waitForResponse(response=>response.url().endsWith('/api/manuals/compile')&&response.status()===201)
    await page.getByRole('button',{name:'Gerar PDF',exact:true}).click()
    assert.equal((await (await generation).json()).revision,3)
    await page.getByRole('dialog').waitFor()
    const generated=page.getByRole('dialog').locator('article').first()
    await generated.getByText('Rev. 03',{exact:true}).waitFor()
    for(const button of ['Enviar para validação','Aprovar documento','Publicar'])await generated.getByRole('button',{name:button,exact:true}).click()
    await generated.getByText('Publicado',{exact:true}).waitFor()
    await page.keyboard.press('Escape')
    const publishedHistory=(await (await admin.get('/api/manuals/versions?developmentId='+dev+'&manualType=proprietario')).json()).versions
    const published=publishedHistory.find(item=>item.status==='publicado')
    assert.equal(published.revision,3)
    assert.equal(publishedHistory.filter(item=>item.status==='publicado').length,1)
    await page.getByRole('link',{name:'Manuais finalizados',exact:true}).click()
    await page.getByRole('heading',{name:'Manuais finalizados',exact:true}).waitFor()
    const finalManual=page.locator('article[data-published-manual-id="'+published.id+'"]')
    await finalManual.waitFor()
    const finalFile='/api/manuals/file?id='+encodeURIComponent(published.id)
    assert.equal(await finalManual.getByRole('link',{name:'Visualizar PDF',exact:true}).getAttribute('href'),finalFile)
    assert.equal(await finalManual.getByRole('link',{name:'Baixar PDF',exact:true}).getAttribute('href'),finalFile+'&download=1')
    for(const old of publishedHistory.filter(item=>item.status!=='publicado'))assert.equal(await page.locator('article[data-published-manual-id="'+old.id+'"]').count(),0)
    assert.ok(!(await (await outsider.get('/manuais')).text()).includes(published.id))
    assert.ok((await (await editor.get('/manuais')).text()).includes(published.id))
    const finalDownload=await admin.get(finalFile);assert.equal(finalDownload.status(),200)
    await fs.writeFile(path.join(directory,'manual-finalizado-proprietario.pdf'),await finalDownload.body())
    await page.screenshot({path:path.join(directory,'manuais-finalizados.png')})
    await require('./manual-technical-api.cjs').runTechnicalApiTests({admin,reviewer,editor,anonymous,outsider,pool,dev,preview})
    await require('./manual-technical-browser.cjs')({page,admin,reviewer,pool,dev,origin,directory,preview})
    const finishingUnits = await require('./manual-finishing-api.cjs')({admin,reviewer,editor,anonymous,outsider,pool,dev,finishingId,directory,preview})
    await require('./manual-finishing-browser.cjs')({page,admin,reviewer,editor,pool,dev,origin,directory,units:finishingUnits})
    await require('./databook-browser.cjs')({page,admin,editor,outsider,anonymous,dev,origin,directory})
    await require('./databook-folder-race.cjs')({admin,pool,dev})
    await require('./manual-public-contract.cjs')({admin,pool,dev})
    await require('./manual-platform-browser.cjs')({browser,dev,origin,directory,adminEmail:'admin-'+suffix+'@example.test'})
    assert.deepEqual(errors,[])
    const ready = await preview('proprietario')
    await fs.writeFile(path.join(directory,'fixture.json'),JSON.stringify({developmentId:dev,organizationId:org,adminEmail:'admin-'+suffix+'@example.test',fingerprint:ready.fingerprint}))
    await fs.writeFile(path.join(directory,'auth.json'),JSON.stringify(await admin.storageState()))
    console.log('MANUAL_COMPOSER_E2E_PASS: manuals, technical text/maintenance, independent unit finishing PDFs, persistent drafts, private Databook uploads/drop/retry/dialogs/races, publication/source conflicts, tenant isolation and stable public API contract')
  } finally { if(browser)await browser.close();await admin.dispose();await reviewer.dispose();await editor.dispose();await anonymous.dispose();await outsider.dispose();await pool.end() }
})().catch(error=>{console.error(error);process.exitCode=1})
