const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { stages, assertImplementationBranch, isolatedConfig, materialFingerprint, materialManifest, materialSnapshot, changedMaterialFiles, validateAttestation } = require('../scripts/release-policy.cjs')
const env = { DG_TEST_DATABASE_URL: 'postgres://test:test@localhost:55439/dg_review_utf8', DG_PREVIEW_FILES_DIR: path.join(os.tmpdir(), 'dg-review-files') }
const passed = () => ({ schemaVersion: 1, status: 'passed', fingerprint: 'abc', stages: stages.map(name => ({ name, status: 'passed' })), matrices: ['internal', 'clients'].map(suite => ({ suite, results: ['mobile', 'tablet', 'desktop'].map(viewport => ({ viewport, passed: ['login', 'read', 'navigation', 'dialog', 'containment'] })) })) })

test('DEH report schema is parseable and requires the review and evidence contract', () => {
  const schemaPath = path.join(__dirname, '..', 'docs', 'engineering-harness', 'review-output.schema.json')
  const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'))
  const required = ['snapshot', 'reviews', 'findings', 'checks', 'visual', 'preview', 'divergences', 'limitations', 'consolidatedBy', 'implementationOwner']
  assert.deepEqual(schema.required, required)
  assert.equal(schema.$defs.snapshot.required.includes('repo'), true)
  assert.equal(schema.$defs.snapshot.required.includes('pr'), true)
  assert.equal(schema.$defs.snapshot.required.includes('baseSha'), true)
  assert.equal(schema.$defs.snapshot.required.includes('headSha'), true)
  assert.deepEqual(schema.$defs.reviewRole.enum, ['DSI', 'Diagnos QA', 'DRAEL', 'LURIEL', 'Security', 'Code Review'])
  assert.deepEqual(schema.properties.reviews.allOf.map(rule => rule.contains.properties.role.const), ['DSI', 'Diagnos QA', 'DRAEL', 'LURIEL', 'Security', 'Code Review'])
  assert.ok(schema.$defs.review.required.includes('snapshotRef'))
  assert.equal(schema.$defs.review.properties.snapshotRef.const, '#/snapshot')
  assert.equal(Object.hasOwn(schema.$defs.review.properties, 'baseSha'), false)
  assert.equal(Object.hasOwn(schema.$defs.review.properties, 'headSha'), false)
  assert.equal(schema.properties.consolidatedBy.const, 'ASTRA')
  assert.equal(schema.properties.implementationOwner.const, 'LUNA')
  assert.ok(schema.$defs.finding.required.includes('evidence'))
  assert.ok(schema.$defs.finding.required.includes('disposition'))
  assert.ok(schema.$defs.evidence.properties.kind.enum.includes('self_attestation'))
  assert.ok(schema.$defs.evidence.properties.kind.enum.includes('static'))
  assert.ok(schema.$defs.check.properties.status.enum.includes('not_run'))
  assert.ok(schema.$defs.check.allOf.some(rule => rule.if.properties.status.const === 'passed' && rule.then.required.includes('evidence')))
  assert.deepEqual(schema.$defs.check.allOf.find(rule => rule.if.properties.status.const === 'passed').then.properties.evidence.properties.kind.enum, ['static', 'command', 'browser', 'preview', 'deployment'])
  assert.ok(schema.$defs.check.allOf.some(rule => rule.if.properties.evidence?.properties?.kind?.const === 'command' && rule.then.required.includes('command')))
  assert.ok(schema.$defs.visual.properties.scenarios.allOf.some(rule => rule.contains.properties.viewport.const === 'mobile'))
  assert.ok(schema.$defs.visual.properties.scenarios.allOf.some(rule => rule.contains.properties.viewport.const === 'tablet'))
  assert.ok(schema.$defs.visual.properties.scenarios.allOf.some(rule => rule.contains.properties.viewport.const === 'desktop'))
  assert.ok(schema.$defs.visualScenario.allOf.some(rule => rule.if.properties.status.const === 'passed' && rule.then.required.includes('evidence')))
  assert.equal(schema.$defs.visualScenario.allOf.find(rule => rule.if.properties.status.const === 'passed').then.properties.evidence.properties.kind.const, 'browser')
  assert.ok(schema.$defs.preview.properties.status.enum.includes('unavailable'))
  assert.ok(schema.$defs.preview.required.includes('deploymentState'))
  assert.ok(schema.$defs.preview.properties.deploymentState.enum.includes('not_applicable'))
  assert.ok(schema.$defs.preview.allOf.some(rule => rule.if.properties.status?.enum?.includes('available') && rule.then.required.includes('evidence') && rule.then.properties.evidence.properties.kind.enum.includes('deployment')))
  assert.ok(schema.$defs.preview.allOf.some(rule => rule.if.properties.deploymentState?.enum?.includes('ready') && rule.then.required.includes('evidence')))
  assert.ok(schema.$defs.preview.allOf.some(rule => rule.if.properties.functionalQa?.const === 'passed' && rule.then.required.includes('evidence')))
  assert.deepEqual(schema.$defs.preview.allOf.find(rule => rule.if.properties.functionalQa?.const === 'passed').then.properties.evidence.properties.kind.enum, ['browser', 'preview'])
})

test('implementation branch allows feature branches and rejects main, detached, and unknown identity', () => {
  assert.equal(assertImplementationBranch('deh/release-policy'), 'deh/release-policy')
  for (const branch of ['main', '', 'HEAD', 'unknown']) assert.throws(() => assertImplementationBranch(branch), /implementation branch/i)
})

test('release fixture bootstrap rejects hosted or shared databases and remote browser URLs', () => {
  assert.equal(isolatedConfig(env).origin, 'http://localhost:3000')
  for (const extra of [{ VERCEL: '1' }, { VERCEL_ENV: 'preview' }, { DG_TEST_DATABASE_URL: 'postgres://test:test@remote.example/dg_review' }, { DG_TEST_DATABASE_URL: 'postgres://test:test@localhost/app' }, { TEST_BASE_URL: 'https://example.com' }, { DG_PREVIEW_FILES_DIR: 'relative' }]) assert.throws(() => isolatedConfig({ ...env, ...extra }))
})
test('release evidence fails closed when stale, failed, incomplete or missing a responsive viewport', () => {
  assert.equal(validateAttestation(passed(), 'abc'), true)
  assert.throws(() => validateAttestation(passed(), 'different'), /stale/)
  const changed = passed(); changed.materialFiles = [{ path: 'scripts/migration-policy.d.mts', sha256: 'old' }]
  assert.throws(() => validateAttestation(changed, 'different', [{ path: 'scripts/migration-policy.d.mts', sha256: 'new' }]), /scripts\/migration-policy\.d\.mts/)
  const failed = passed(); failed.status = 'failed'; assert.throws(() => validateAttestation(failed, 'abc'))
  const incomplete = passed(); incomplete.stages = incomplete.stages.filter(stage => stage.name !== 'audit-runtime'); assert.throws(() => validateAttestation(incomplete, 'abc'), /audit-runtime/)
  const missing = passed(); missing.matrices[0].results.pop(); assert.throws(() => validateAttestation(missing, 'abc'), /desktop/)
})
test('material fingerprint covers new source/test/config files and excludes documentation/attestation churn', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'dg-release-policy-'))
  try {
    fs.mkdirSync(path.join(root, 'app')); fs.mkdirSync(path.join(root, 'tests')); fs.mkdirSync(path.join(root, 'scripts')); fs.mkdirSync(path.join(root, 'hooks')); fs.mkdirSync(path.join(root, '.qa'))
    fs.writeFileSync(path.join(root, 'app', 'page.tsx'), 'source\r\nline\r\n'); fs.writeFileSync(path.join(root, 'scripts', 'migration-policy.d.mts'), 'declare const migration: string\r\n'); fs.writeFileSync(path.join(root, 'package.json'), '{}')
    const before = materialFingerprint(root), beforeManifest = materialManifest(root)
    assert.ok(beforeManifest.some(file => file.path === 'scripts/migration-policy.d.mts'))
    fs.writeFileSync(path.join(root, 'app', 'page.tsx'), 'source\nline\n'); assert.equal(materialFingerprint(root), before, 'Windows CRLF and Linux LF must attest the same material sources')
    fs.writeFileSync(path.join(root, 'scripts', 'migration-policy.d.mts'), 'declare const migration: string\n'); assert.equal(materialFingerprint(root), before, 'TypeScript .mts declaration files must normalize Windows CRLF and Linux LF')
    assert.deepEqual(materialManifest(root), beforeManifest, 'The diagnostic manifest must use the same normalized source bytes')
    fs.writeFileSync(path.join(root, 'README.md'), 'doc'); fs.writeFileSync(path.join(root, '.qa', 'release-attestation.json'), '{}')
    fs.writeFileSync(path.join(root, 'scripts', 'RELEASE.md'), 'operational documentation')
    assert.equal(materialFingerprint(root), before)
    assert.deepEqual(changedMaterialFiles(beforeManifest, materialManifest(root)), [])
    fs.writeFileSync(path.join(root, 'tests', 'future.test.ts'), 'new regression')
    assert.notEqual(materialFingerprint(root), before); assert.deepEqual(changedMaterialFiles(beforeManifest, materialManifest(root)), ['tests/future.test.ts'])
    const tests = materialFingerprint(root); fs.writeFileSync(path.join(root, 'package.json'), '{"changed":true}')
    assert.notEqual(materialFingerprint(root), tests); assert.deepEqual(changedMaterialFiles(beforeManifest, materialManifest(root)), ['package.json', 'tests/future.test.ts'])
    const config = materialFingerprint(root); fs.writeFileSync(path.join(root, 'hooks', 'use-review.ts'), 'export const useReview = () => true')
    assert.notEqual(materialFingerprint(root), config)
  } finally {
    const target = fs.realpathSync(root)
    assert.equal(path.dirname(target), fs.realpathSync(os.tmpdir()))
    assert.ok(path.basename(target).startsWith('dg-release-policy-'))
    fs.rmSync(target, { recursive: true, force: true })
  }
})

test('hosted verification ignores only Vercel config absent from the attested source tree', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'dg-vercel-source-'))
  try {
    fs.mkdirSync(path.join(root, 'app'))
    fs.writeFileSync(path.join(root, 'app', 'page.tsx'), 'source\n')
    const sourceManifest = materialManifest(root)
    const sourceFingerprint = materialFingerprint(root)
    fs.writeFileSync(path.join(root, 'vercel.json'), '{"generated":true}\n')

    const generated = materialSnapshot(root, sourceManifest, { VERCEL: '1' })
    assert.equal(generated.fingerprint, sourceFingerprint)
    assert.deepEqual(generated.materialFiles, sourceManifest)
    const unexpectedLocalConfig = materialSnapshot(root, sourceManifest, {})
    assert.notEqual(unexpectedLocalConfig.fingerprint, sourceFingerprint)
    assert.deepEqual(changedMaterialFiles(sourceManifest, unexpectedLocalConfig.materialFiles), ['vercel.json'])

    const versionedManifest = materialManifest(root)
    const versionedFingerprint = materialFingerprint(root)
    fs.writeFileSync(path.join(root, 'vercel.json'), '{"generated":false}\n')
    const versioned = materialSnapshot(root, versionedManifest, { VERCEL: '1' })
    assert.notEqual(versioned.fingerprint, versionedFingerprint)
    assert.deepEqual(changedMaterialFiles(versionedManifest, versioned.materialFiles), ['vercel.json'])
  } finally {
    const target = fs.realpathSync(root)
    assert.equal(path.dirname(target), fs.realpathSync(os.tmpdir()))
    fs.rmSync(target, { recursive: true, force: true })
  }
})
